### ISSUE TITLE
How to get LastEvaluatedKey

### ISSUE THREAD

**Issue by Arttii** [vsco/domino#38]
Hi,

I cannot seem to figure out how to get access to LastEvaluatedKey, to be able to resume the query to do pagination in an api for a range query.

Thanks

**Comment by negator** [comment]
Hello. The LastEvaluatedKey isn't exposed on purpose, a the intent was to abstract paging away from consumers. Instead you can use the `StreamWithChannel` function to stream results: https://github.com/vsco/domino#streaming-results---allows-for-lazy-data-fetching-and-consuming

Please let me know if this does/doesn't suit your needs. Thanks!

**Comment by Arttii** [comment]
Thanks for the reply. How does that work out for request response type of usecaseses though.

Say I'm running this in lambda and serving a frontend. How would the channel  fit that usecase? Conceptually if there's the results functiin, should it also expose this type of results? Or I'm just misunderstanding the concept?
________________________________

**Comment by Arttii** [comment]
Let say a user hits an endpoint to fetch a range of todos, and there are like 1000, so you want to paginate the results, so that they don't wait for the request too long, think infinite scroll.
What I understood, the way to do this in a stateless  way, is to set limit to 10 for example and send the last evaluated key back to the client and keep the state there, with the client sending it to the Backend on subsequent requests.

The thing is, you can only know if there are more results outside the limit you set, if the Last Evaluated Key is exposed.

Or am I thinking about this wrong?

________________________________

**Comment by negator** [comment]
I see, you would like paginate results in a table without a range key or secondary index, i.e. scanning an entire table and paging results back to clients. 

Typically you would utilize a range key or index (local or global secondary). For example if the index held timestamps, your pagination key would be the time stamp of the last element in last result, rather than the LastEvaluatedKey, however this is a valid access pattern. 

It should be an easy change to expose the LastEvaluatedKey, but I won’t be able to get to it until next week. A workaround for you, if you need it immediately, would be to use the Build function https://github.com/vsco/domino/blob/master/domino.go#L1146, which returns input for use directly against the AWS provided dynamodb library. 

Thank you for the report.

**Comment by Arttii** [comment]
Thanks. Well I am using the range key the question is how do I know that there are more results to fetch? Just retry the request and if it's empty do nothing?
I guess that's an option. Thanks for the clarification.
________________________________

**Comment by negator** [comment]
You could do that. Another strategy I’ve seen work well, is to specify the Limit as the requested limit+1.

**Comment by Arttii** [comment]
So the approach with using Build works out. I am still not quite clear what the best approach is, conceptually returning an empty set is also quite feasible, as well as Limit, but this is a bit redundant on some level as in the case of Limit+1, one would need to check if the len is +1 and then return back, that knowledge or in the first case kinda waste some backend calls?
I would think its cleaner to expose the LastEvaluatedKey in which case  you can either use that value for the next call or just send back something like `thereisMore:true`.

**Comment by negator** [comment]
Both workarounds (empty result set and limit+1) will consume read capacity, albeit very small. Although dynamodb is typically used in tandem with a read-through cache so it tends to be less of an issue. Additionally, the use of LastEvaluatedKey narrows your caching opportunity and efficiency for certain use cases such as overlapping range queries (which is why it was overlooked here). 

Nevertheless, not using a cache is a totally valid usecase, and LastEvaluatedKey should be exposed.

**Comment by negator** [comment]
Please upgrade to this version, https://github.com/vsco/domino/releases/tag/v1.0.3.

You now have the ability to set and retrieve the LastEvaludatedKey for queries and scans.

https://github.com/vsco/domino/blob/master/domino.go#L1120
https://github.com/vsco/domino/blob/master/domino.go#L1250


Closing this for now. 

Thanks for the report :)
